import type { Bank } from "./types";

export const bankColors = [
  "#33477A",
  "#2F6F4E",
  "#B8862B",
  "#C41F35",
  "#5A4A8C",
  "#2F7A7A",
  "#8C5A2F",
  "#4A6741",
  "#7A3B69",
  "#3B6B8C",
  "#6B4A3B",
  "#5C7A2F",
];

const baseBanks = [
  { id: "garanti-bbva", name: "Garanti BBVA", grade: "A+", rate: 47.2, app: 9.5, rating: 4.8, reviewCount: 5210,
    quote: "\"BonusFlaş kampanyaları ve hızlı EFT'lerle bankacılığı oyunlaştırıyor.\"",
    sub: { branch: 4.6, service: 4.35, app: 4.9, atm: 4.7, security: 4.85 }, hasBranch: true, creditApprovalRate: 79.6, creditApprovalCount: 1823,
    summary: "Mobil uygulama ve kredi kartı avantajlarında sınıfın açık ara lideri." },
  { id: "akbank", name: "Akbank", grade: "A+", rate: 47.0, app: 9.4, rating: 4.7, reviewCount: 4890,
    quote: "\"Akbank Mobil ile şube ihtiyacı neredeyse kalmadı.\"",
    sub: { branch: 4.35, service: 4.6, app: 4.9, atm: 4.53, security: 4.8 }, hasBranch: true, creditApprovalRate: 77.4, creditApprovalCount: 1712,
    summary: "Dijital ve şube deneyimini dengeli götüren birkaç bankadan biri." },
  { id: "yapikredi", name: "Yapı Kredi", grade: "A", rate: 46.4, app: 9.1, rating: 4.5, reviewCount: 3760,
    quote: "\"World kart avantajları hâlâ pazarın en güçlülerinden.\"",
    sub: { branch: 4.1, service: 4.1, app: 4.6, atm: 4.3, security: 4.55 }, hasBranch: true, creditApprovalRate: 73.0, creditApprovalCount: 1316,
    summary: "Kredi kartı ekosistemiyle öne çıkıyor, şube kuyrukları zaman zaman uzuyor." },
  { id: "isbankasi", name: "İş Bankası", grade: "A", rate: 46.0, app: 8.9, rating: 4.4, reviewCount: 4120,
    quote: "\"En eski banka ama uygulaması son yıllarda gerçekten toparladı.\"",
    sub: { branch: 4.9, service: 4.35, app: 4.1, atm: 4.65, security: 4.25 }, hasBranch: true, creditApprovalRate: 70.8, creditApprovalCount: 1442,
    summary: "Şube ağı ve kurumsal güven en güçlü yanı, mobil tarafta rakiplerini yakalıyor." },
  { id: "ziraatbankasi", name: "Ziraat Bankası", grade: "A-", rate: 45.5, app: 8.5, rating: 4.3, reviewCount: 4980,
    quote: "\"Türkiye'nin her köşesinde şubesi var, bu hâlâ büyük bir avantaj.\"",
    sub: { branch: 4.9, service: 4.1, app: 3.85, atm: 4.6, security: 4.08 }, hasBranch: true, creditApprovalRate: 68.6, creditApprovalCount: 1743,
    summary: "Devasa şube ağıyla kırsalda bile erişim sağlıyor, mobil deneyim gelişiyor." },
  { id: "halkbank", name: "Halkbank", grade: "B+", rate: 44.8, app: 7.9, rating: 4.0, reviewCount: 3105,
    quote: "\"KOBİ kredilerinde hâlâ ilk akla gelen banka.\"",
    sub: { branch: 4.6, service: 3.85, app: 3.6, atm: 4.3, security: 3.8 }, hasBranch: true, creditApprovalRate: 62.0, creditApprovalCount: 1087,
    summary: "Esnaf ve KOBİ kredilerinde güçlü, dijital deneyimde gelişim payı var." },
  { id: "vakifbank", name: "VakıfBank", grade: "B+", rate: 44.9, app: 8.0, rating: 4.1, reviewCount: 2870,
    quote: "\"Konut kredisi kampanyaları düzenli takip etmeye değer.\"",
    sub: { branch: 4.35, service: 3.85, app: 3.85, atm: 4.22, security: 3.97 }, hasBranch: true, creditApprovalRate: 64.2, creditApprovalCount: 1004,
    summary: "Konut kredisi kampanyalarıyla öne çıkıyor, çağrı merkezi yoğun saatlerde yavaş." },
  { id: "qnb-finansbank", name: "QNB Finansbank", grade: "A-", rate: 45.6, app: 8.7, rating: 4.3, reviewCount: 2640,
    quote: "\"CepteTeklif ile anlık kampanya takibi gerçekten işe yarıyor.\"",
    sub: { branch: 3.85, service: 4.1, app: 4.35, atm: 4.08, security: 4.32 }, hasBranch: true, creditApprovalRate: 68.6, creditApprovalCount: 924,
    summary: "Kişiselleştirilmiş kampanyalarıyla dijital tarafta iddialı bir banka." },
  { id: "denizbank", name: "DenizBank", grade: "A-", rate: 45.2, app: 8.6, rating: 4.2, reviewCount: 2410,
    quote: "\"DenizBank Mobil'in arayüzü sade ve hızlı.\"",
    sub: { branch: 4.1, service: 4.1, app: 4.35, atm: 4.15, security: 4.28 }, hasBranch: true, creditApprovalRate: 66.4, creditApprovalCount: 844,
    summary: "Orta ölçekli bankalar arasında dijital deneyimde öne çıkıyor." },
  { id: "teb", name: "TEB", grade: "B+", rate: 44.3, app: 8.1, rating: 4.0, reviewCount: 1980,
    quote: "\"BNP Paribas ortaklığı kurumsal bankacılıkta güven veriyor.\"",
    sub: { branch: 3.85, service: 4.1, app: 4.1, atm: 3.92, security: 4.05 }, hasBranch: true, creditApprovalRate: 62.0, creditApprovalCount: 693,
    summary: "Kurumsal ve KOBİ bankacılığında güçlü, bireysel şube sayısı sınırlı." },
  { id: "ing-bank", name: "ING Bank", grade: "A-", rate: 45.3, app: 8.8, rating: 4.3, reviewCount: 2260,
    quote: "\"Şubesiz model ama Türkiye'de en eski dijital oyunculardan biri.\"",
    sub: { branch: 3.35, service: 4.1, app: 4.6, atm: 3.83, security: 4.45 }, hasBranch: true, creditApprovalRate: 68.6, creditApprovalCount: 791,
    summary: "Az şubeyle güçlü dijital deneyim sunuyor, yoğun şehirlerde erişim sınırlı." },
  { id: "sekerbank", name: "Şekerbank", grade: "B", rate: 43.6, app: 7.3, rating: 3.8, reviewCount: 940,
    quote: "\"Tarım kredilerinde bölgesinde hâlâ tercih ediliyor.\"",
    sub: { branch: 3.85, service: 3.6, app: 3.35, atm: 3.83, security: 3.58 }, hasBranch: true, creditApprovalRate: 57.6, creditApprovalCount: 329,
    summary: "Bölgesel ve tarım odaklı kredilerde niş bir oyuncu, dijital tarafta geride." },
  { id: "kuveyt-turk", name: "Kuveyt Türk", grade: "A-", rate: 45.4, app: 8.7, rating: 4.4, reviewCount: 2890,
    quote: "\"Katılım bankacılığında uygulama kalitesiyle de öne çıkıyor.\"",
    sub: { branch: 4.1, service: 4.1, app: 4.35, atm: 4.25, security: 4.38 }, hasBranch: true, creditApprovalRate: 70.8, creditApprovalCount: 1011,
    summary: "En büyük katılım bankası unvanını dijital deneyimle de destekliyor." },
  { id: "albaraka-turk", name: "Albaraka Türk", grade: "B+", rate: 44.5, app: 7.8, rating: 4.0, reviewCount: 1340,
    quote: "\"Kâr payı oranları düzenli karşılaştırmaya değer.\"",
    sub: { branch: 3.85, service: 3.85, app: 3.85, atm: 3.92, security: 3.92 }, hasBranch: true, creditApprovalRate: 62.0, creditApprovalCount: 469,
    summary: "Katılım bankacılığında istikrarlı ama dijital tarafta gelişim payı var." },
  { id: "turkiye-finans", name: "Türkiye Finans", grade: "B+", rate: 44.6, app: 7.9, rating: 4.0, reviewCount: 1510,
    quote: "\"N Kolay ile dijital tarafını büyütmeye çalışıyor.\"",
    sub: { branch: 3.85, service: 3.85, app: 3.85, atm: 3.92, security: 3.92 }, hasBranch: true, creditApprovalRate: 62.0, creditApprovalCount: 528,
    summary: "Geleneksel şube ağını N Kolay'ın dijital deneyimiyle tamamlıyor." },
  { id: "ziraat-katilim", name: "Ziraat Katılım", grade: "B+", rate: 44.7, app: 7.7, rating: 3.9, reviewCount: 1180,
    quote: "\"Devlet güvencesi katılım bankacılığında tercih sebebi oluyor.\"",
    sub: { branch: 4.1, service: 3.85, app: 3.6, atm: 4.0, security: 3.75 }, hasBranch: true, creditApprovalRate: 59.8, creditApprovalCount: 413,
    summary: "Ziraat'in şube ağından güç alıyor, uygulama arayüzü sadeleştirilebilir." },
  { id: "vakif-katilim", name: "Vakıf Katılım", grade: "B", rate: 44.0, app: 7.4, rating: 3.8, reviewCount: 890,
    quote: "\"Konut finansmanında kâr payı oranları takip edilmeye değer.\"",
    sub: { branch: 3.85, service: 3.6, app: 3.6, atm: 3.83, security: 3.7 }, hasBranch: true, creditApprovalRate: 57.6, creditApprovalCount: 312,
    summary: "Konut finansmanı odaklı kampanyalarıyla dikkat çekiyor." },
  { id: "emlak-katilim", name: "Emlak Katılım", grade: "B", rate: 43.8, app: 7.2, rating: 3.7, reviewCount: 620,
    quote: "\"Genç bir banka ama gayrimenkul finansmanında hızlı büyüyor.\"",
    sub: { branch: 3.35, service: 3.35, app: 3.6, atm: 3.53, security: 3.65 }, hasBranch: true, creditApprovalRate: 55.4, creditApprovalCount: 217,
    summary: "Katılım bankacılığının en yeni oyuncularından, şube ağı hâlâ küçük." },
  { id: "enpara", name: "Enpara", grade: "A", rate: 46.5, app: 9.3, rating: 4.6, reviewCount: 3340,
    quote: "\"Şubesi yok ama QNB Finansbank güvencesiyle işlem yapıyorsun.\"",
    sub: { branch: null, service: 4.35, app: 4.9, atm: null, security: 4.75 }, hasBranch: false, creditApprovalRate: 75.2, creditApprovalCount: 1169,
    summary: "Şubesiz bankacılıkta faiz oranı ve uygulama kalitesini birlikte sunan nadir örnek." },
  { id: "on-dijital", name: "ON Dijital", grade: "B+", rate: 44.9, app: 8.3, rating: 4.1, reviewCount: 980,
    quote: "\"TEB'in dijital markası, genç kullanıcıları hedefliyor.\"",
    sub: { branch: null, service: 3.85, app: 4.1, atm: null, security: 4.1 }, hasBranch: false, creditApprovalRate: 64.2, creditApprovalCount: 343,
    summary: "Dijital-öncelikli deneyimiyle genç kullanıcı kitlesine hitap ediyor." },
  { id: "n-kolay", name: "N Kolay", grade: "B", rate: 44.2, app: 8.0, rating: 3.9, reviewCount: 710,
    quote: "\"Türkiye Finans'ın dijital yüzü, açılış süreci gerçekten hızlı.\"",
    sub: { branch: null, service: 3.6, app: 3.85, atm: null, security: 3.88 }, hasBranch: false, creditApprovalRate: 59.8, creditApprovalCount: 248,
    summary: "Katılım bankacılığını dijital-öncelikli bir deneyimle sunuyor." },
  { id: "odeabank", name: "Odeabank", grade: "B", rate: 43.9, app: 7.5, rating: 3.8, reviewCount: 860,
    quote: "\"Mevduat kampanyalarını düzenli takip edenler kazançlı çıkıyor.\"",
    sub: { branch: 3.35, service: 3.6, app: 3.6, atm: 3.58, security: 3.7 }, hasBranch: true, creditApprovalRate: 57.6, creditApprovalCount: 301,
    summary: "Zaman zaman öne çıkan mevduat kampanyalarıyla dikkat çekiyor." },
  { id: "alternatif-bank", name: "Alternatif Bank", grade: "B-", rate: 42.8, app: 6.9, rating: 3.6, reviewCount: 480,
    quote: "\"Küçük ama kurumsal bankacılıkta niş bir oyuncu.\"",
    sub: { branch: 3.35, service: 3.6, app: 3.35, atm: 3.48, security: 3.48 }, hasBranch: true, creditApprovalRate: 53.2, creditApprovalCount: 168,
    summary: "Kurumsal bankacılığa odaklı, bireysel şube deneyimi sınırlı." },
  { id: "anadolubank", name: "Anadolubank", grade: "B-", rate: 42.5, app: 6.8, rating: 3.5, reviewCount: 410,
    quote: "\"Bölgesel sanayi bölgelerinde ismi geçen bir banka.\"",
    sub: { branch: 3.35, service: 3.6, app: 3.35, atm: 3.42, security: 3.42 }, hasBranch: true, creditApprovalRate: 51.0, creditApprovalCount: 144,
    summary: "Sanayi bölgelerinde kurumsal ilişkileriyle biliniyor, dijital tarafı sade." },
  { id: "fibabanka", name: "Fibabanka", grade: "B", rate: 43.7, app: 7.6, rating: 3.9, reviewCount: 730,
    quote: "\"Fibabanka Cep'in arayüzü küçük bankaya göre oldukça iyi.\"",
    sub: { branch: 3.35, service: 3.6, app: 3.85, atm: 3.62, security: 3.88 }, hasBranch: true, creditApprovalRate: 59.8, creditApprovalCount: 255,
    summary: "Küçük ölçeğine rağmen mobil deneyimde şaşırtıcı derecede iyi." },
  { id: "burgan-bank", name: "Burgan Bank", grade: "B-", rate: 42.6, app: 6.9, rating: 3.6, reviewCount: 390,
    quote: "\"Kuveyt sermayeli, kurumsal bankacılıkta temkinli büyüyor.\"",
    sub: { branch: 3.1, service: 3.6, app: 3.35, atm: 3.35, security: 3.48 }, hasBranch: true, creditApprovalRate: 53.2, creditApprovalCount: 136,
    summary: "Temkinli büyüme stratejisiyle küçük ama istikrarlı bir portföy sunuyor." },
  { id: "icbc-turkey", name: "ICBC Turkey", grade: "B-", rate: 42.3, app: 6.7, rating: 3.5, reviewCount: 310,
    quote: "\"Çin sermayeli, daha çok kurumsal ve proje finansmanına odaklı.\"",
    sub: { branch: 3.1, service: 3.35, app: 3.35, atm: 3.3, security: 3.42 }, hasBranch: true, creditApprovalRate: 51.0, creditApprovalCount: 108,
    summary: "Bireysel bankacılıktan çok proje finansmanında tercih ediliyor." },
  { id: "hsbc-turkiye", name: "HSBC Türkiye", grade: "B", rate: 43.5, app: 7.6, rating: 3.9, reviewCount: 1020,
    quote: "\"Küçülen şube ağına rağmen kart avantajları hâlâ güçlü.\"",
    sub: { branch: 3.35, service: 3.6, app: 3.85, atm: 3.62, security: 3.88 }, hasBranch: true, creditApprovalRate: 59.8, creditApprovalCount: 357,
    summary: "Şube ağını daraltsa da kredi kartı avantajlarını koruyor." },
  { id: "aktif-bank", name: "Aktif Bank", grade: "C+", rate: 41.5, app: 6.5, rating: 3.4, reviewCount: 560,
    quote: "\"Cepte Kolay uygulaması ile şubesiz açılışta öncülerden.\"",
    sub: { branch: null, service: 3.1, app: 3.6, atm: null, security: 3.5 }, hasBranch: false, creditApprovalRate: 48.8, creditApprovalCount: 196,
    summary: "Yatırım bankacılığı kökenli, şubesiz bireysel bankacılıkta erken hareket etti." },
  { id: "tom-bank", name: "TOM Bank", grade: "C+", rate: 41.2, app: 6.8, rating: 3.5, reviewCount: 340,
    quote: "\"Yeni nesil dijital banka, arayüzü genç kullanıcıya hitap ediyor.\"",
    sub: { branch: null, service: 3.1, app: 3.85, atm: null, security: 3.67 }, hasBranch: false, creditApprovalRate: 51.0, creditApprovalCount: 119,
    summary: "Yeni kurulan dijital bankalar arasında hızlı büyüyen bir isim." },
  { id: "colendi-bank", name: "Colendi Bank", grade: "C+", rate: 41.0, app: 6.9, rating: 3.4, reviewCount: 290,
    quote: "\"Fintech kökeninden geliyor, kredi skorlama tarafı ilgi çekici.\"",
    sub: { branch: null, service: 3.1, app: 3.6, atm: null, security: 3.5 }, hasBranch: false, creditApprovalRate: 48.8, creditApprovalCount: 102,
    summary: "Fintech geçmişinden gelen alternatif kredi değerlendirme modeliyle dikkat çekiyor." },
  { id: "hayat-finans", name: "Hayat Finans", grade: "C+", rate: 40.8, app: 6.4, rating: 3.3, reviewCount: 210,
    quote: "\"En yeni katılım bankalarından, ürün yelpazesi hâlâ genişliyor.\"",
    sub: { branch: 3.1, service: 3.1, app: 3.35, atm: 3.2, security: 3.33 }, hasBranch: true, creditApprovalRate: 46.6, creditApprovalCount: 74,
    summary: "Katılım bankacılığının en genç oyuncusu, ürün çeşitliliği hâlâ sınırlı." },
];

export const demoBanks: Bank[] = baseBanks.map((bank, index) => ({
  ...bank,
  color: bankColors[index % bankColors.length],
  order: index,
}));

export function bankLogoPath(bankId: string): string {
  return `/bank-logos/${bankId}.svg`;
}
