"use client";
import { useEffect, useMemo, useState } from "react";
import { getIdTokenResult } from "firebase/auth";
import Header from "./Header";import Footer from "./Footer";import AuthModal from "./AuthModal";import ProfileModal from "./ProfileModal";
import { useAuth } from "@/lib/auth-context";import { useReviews } from "@/lib/reviews-context";import { useToast } from "@/lib/toast-context";import { useUI } from "@/lib/ui-context";
import { approveReview, deleteReview, hideReview, migrateSensitiveReviewData } from "@/lib/reviews";import { isReviewUnderModeration } from "@/lib/moderation";
export default function AdminModeration(){
 const{user}=useAuth();const{reviews}=useReviews();const{showToast}=useToast();const{openAuthModal}=useUI();const[isAdmin,setIsAdmin]=useState(false);const[checking,setChecking]=useState(true);const[busyId,setBusyId]=useState<string|null>(null);const[privacyBusy,setPrivacyBusy]=useState(false);
 useEffect(()=>{let alive=true;(async()=>{setChecking(true);try{if(!user){if(alive)setIsAdmin(false);return;}const token=await getIdTokenResult(user,true).catch(()=>null);if(alive)setIsAdmin(token?.claims?.admin===true);}finally{if(alive)setChecking(false);}})();return()=>{alive=false;};},[user]);
 const reportedReviews=useMemo(()=>reviews.filter(r=>r.reportCount>0||r.status==="hidden").sort((a,b)=>(isReviewUnderModeration(b)?1:0)-(isReviewUnderModeration(a)?1:0)||b.reportCount-a.reportCount),[reviews]);
 const sensitiveReviewCount=useMemo(()=>reviews.filter(r=>r.employmentStatus||r.findeksScoreRange).length,[reviews]);
 async function runAction(id:string,action:"approve"|"hide"|"delete"){setBusyId(id);try{if(action==="approve")await approveReview(id);if(action==="hide")await hideReview(id);if(action==="delete")await deleteReview(id);showToast("Moderasyon işlemi tamamlandı.");}catch(err){showToast(err instanceof Error?err.message:"İşlem yapılamadı.");}finally{setBusyId(null);}}
 async function handlePrivacyMigration(){setPrivacyBusy(true);try{const migrated=await migrateSensitiveReviewData(reviews);showToast(migrated?`${migrated} yorumdaki hassas alan özel koleksiyona taşındı.`:"Taşınacak hassas yorum alanı bulunamadı.");}catch(err){showToast(err instanceof Error?err.message:"Gizlilik taşıması tamamlanamadı.");}finally{setPrivacyBusy(false);}}
 return <><Header/><main className="legal-page"><div className="wrap"><section className="admin-card"><h1>Moderasyon Paneli</h1><p>Bildirim alan yorumları kontrol edin. Yönetici erişimi yalnızca Firebase <strong>admin custom claim</strong> ile doğrulanır.</p>{!user&&<div className="info-strip" style={{margin:"18px 0"}}>Moderasyon için giriş yapmalısın. <button className="text-link-btn" style={{display:"inline",margin:0}} onClick={()=>openAuthModal("login")}>Giriş yap</button></div>}{user&&checking&&<p className="skeleton-row">Yetki kontrol ediliyor…</p>}{user&&!checking&&!isAdmin&&<div className="info-strip" style={{margin:"18px 0"}}>Bu hesap moderasyon yetkisine sahip değil. Yetkili hesapla giriş yapın.</div>}{isAdmin&&<div><div className="admin-privacy-card"><div><h2>Hassas Veri Temizliği</h2><p>Eski yorumlarda açık koleksiyonda kalan çalışma durumu ve Findeks aralığını yalnızca kullanıcı/yönetici tarafından okunabilen özel alana taşır.</p></div><button type="button" className="btn primary" onClick={handlePrivacyMigration} disabled={privacyBusy||sensitiveReviewCount===0}>{privacyBusy?"Taşınıyor…":`Gizliye Taşı (${sensitiveReviewCount})`}</button></div><h2>Bildirim Alan Yorumlar</h2>{reportedReviews.length===0?<p className="skeleton-row">Şu anda incelenecek yorum yok.</p>:reportedReviews.map(r=><div className="admin-review" key={r.id}><p><strong>{r.bankName}</strong> — {r.userName}<span className="badge-soft">{r.reportCount} bildirim</span>{isReviewUnderModeration(r)&&<span className="badge-soft badge-alert">öncelikli inceleme</span>}{r.status==="hidden"&&<span className="badge-soft">gizli</span>}</p><p>{r.text}</p><div className="admin-actions"><button className="btn small primary" disabled={busyId===r.id} onClick={()=>runAction(r.id,"approve")}>Yayında Tut</button><button className="btn small" disabled={busyId===r.id} onClick={()=>runAction(r.id,"hide")}>Gizle</button><button className="btn small" disabled={busyId===r.id} onClick={()=>runAction(r.id,"delete")}>Sil</button></div></div>)}</div>}</section></div></main><Footer/><AuthModal/><ProfileModal/></>;
}
