"use client";
import { useMemo } from "react";import { useBanks } from "@/lib/banks-context";import { useReviews } from "@/lib/reviews-context";
import { applyReviewStatsToBanks, MIN_APPROVAL_SAMPLE_COUNT, MIN_RELIABLE_REVIEW_COUNT, visibleReviews } from "@/lib/bank-stats";
import { gradeClassOf, letterFromScore } from "@/lib/grades";import { CATEGORY_META } from "@/lib/types";import BankLogo from "./BankLogo";import RateBankButton from "./RateBankButton";
export default function Hero(){
 const{banks}=useBanks();const{reviews,loading:reviewsLoading}=useReviews();const updated=useMemo(()=>applyReviewStatsToBanks(banks,reviews),[banks,reviews]);const liveReviews=useMemo(()=>visibleReviews(reviews).filter(r=>r.status!=="hidden"),[reviews]);
 const stats=useMemo(()=>{const reviewCount=liveReviews.length;const avg=reviewCount?(liveReviews.reduce((s,r)=>s+r.stars,0)/reviewCount).toFixed(1):"0.0";return{bankCount:updated.length,reviewCount,avg};},[updated.length,liveReviews]);
 const topBank=useMemo(()=>{const reviewed=updated.filter(b=>b.reviewCount>0);const reliableBanks=reviewed.filter(b=>b.reviewCount>=MIN_RELIABLE_REVIEW_COUNT);const pool=reliableBanks.length?reliableBanks:reviewed;return pool.length?[...pool].sort((a,b)=>b.rating-a.rating||b.reviewCount-a.reviewCount)[0]:null;},[updated]);const reliable=(topBank?.reviewCount??0)>=MIN_RELIABLE_REVIEW_COUNT;
 return <section className="hero"><div className="hero-shell wrap"><div className="hero-grid"><div><div className="eyebrow">Bağımsız banka değerlendirme platformu</div><h1>Bankaları <em>gerçek kullanıcı deneyimleriyle</em> karşılaştırın.</h1><p className="lead">Mobil uygulama, müşteri hizmetleri, ATM, güvenlik, şube hizmetleri ve kredi/kart başvuru sonuçlarını tek ekranda görün.</p><div className="hero-mini-list"><span>Canlı kullanıcı puanları</span><span>Kategori bazlı karne sistemi</span><span>Kredi ve kart onay deneyimleri</span></div><div className="hero-ctas"><button className="btn primary" onClick={()=>document.getElementById("karsilastir")?.scrollIntoView({behavior:"smooth"})}>Bankaları Karşılaştır</button><RateBankButton className="btn hero-rate-btn"><span className="hero-rate-icon" aria-hidden="true">★</span><span>Bankanı Puanla</span></RateBankButton></div><div className="hero-stats hero-stats-pro"><div><span className="num">{stats.bankCount}</span><span className="lbl">Takip Edilen Banka</span></div><div><span className="num">{reviewsLoading?"—":stats.reviewCount.toLocaleString("tr-TR")}</span><span className="lbl">Yayındaki Kullanıcı Yorumu</span></div><div><span className="num">{reviewsLoading?"—":stats.avg}</span><span className="lbl">Ortalama Kullanıcı Puanı</span></div></div></div>
 {reviewsLoading?<div className="report-card report-card-empty"><div className="hero-card-skeleton" aria-label="Karne hazırlanıyor"><span className="skeleton-line wide"/><span className="skeleton-line"/><span className="skeleton-line short"/></div></div>:topBank?<div className={`report-card report-card-pro${reliable?" reliable-sample":" emerging-sample"}`}><div className="rc-topline">{reliable?"Verisi güçlenen banka karnesi":"Karne verisi oluşuyor"}</div><div className="rc-head"><div className="bank-cell"><BankLogo bank={topBank}/><div><div className="rc-bank">{topBank.name}</div><div className="rc-sub">{topBank.reviewCount.toLocaleString("tr-TR")} GERÇEK YORUM{!reliable&&` · GÜVEN ROZETİ İÇİN ${MIN_RELIABLE_REVIEW_COUNT} YORUM`}</div></div></div><div className="rc-stamp">{topBank.grade}</div></div>{CATEGORY_META.filter(c=>topBank.sub[c.key]!==null).map(c=>{const l=letterFromScore(topBank.sub[c.key] as number);return <div className="rc-row" key={c.key}><span className="subj">{c.label}</span><span className={`rc-grade ${gradeClassOf(l)}`}>{l}</span></div>;})}{topBank.creditApprovalCount>=MIN_APPROVAL_SAMPLE_COUNT&&<div className="rc-row"><span className="subj">Kredi/Kredi Kartı Onayı</span><span className="rc-grade g-A">%{Math.round(topBank.creditApprovalRate)}</span></div>}<div className="rc-note"><span className="rc-note-label">Veri notu</span>{reliable?`Bu karne ${topBank.reviewCount.toLocaleString("tr-TR")} yayınlanmış gerçek kullanıcı yorumuna dayanır.`:`Sonuçlar henüz küçük bir örnekleme dayanıyor. Liderlik ve güçlü veri rozetleri en az ${MIN_RELIABLE_REVIEW_COUNT} yorumdan sonra açılır.`}</div></div>:<div className="report-card report-card-empty"><div className="rc-stamp" style={{margin:"0 auto 16px"}}>?</div><p style={{textAlign:"center",fontWeight:700,marginBottom:"8px"}}>Henüz kullanıcı puanı yok</p><p style={{textAlign:"center",fontSize:"13px",color:"var(--ink-soft)",marginBottom:"16px"}}>İlk puanı ve yorumunu bırak, karneyi sen başlat.</p><RateBankButton className="btn primary" disabled={banks.length===0}>İlk Bankayı Puanla</RateBankButton></div>}</div></div></section>;
}
